---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: google-postgresql
  labels:
    provider: google
    db: postgresql
spec:
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQL
  mode: Pipeline
  pipeline:
  - step: create-sql
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: sql
        base:
          apiVersion: sql.gcp.m.upbound.io/v1beta1
          kind: DatabaseInstance
          spec:
            forProvider:
              databaseVersion: "POSTGRES_13"
              deletionProtection: false
              region: us-east1
              rootPasswordSecretRef:
                name: my-db-password
                key: password
              settings:
                availabilityType: REGIONAL
                tier: db-custom-1-3840
                backupConfiguration:
                  enabled: true
                  binaryLogEnabled: false
                ipConfiguration:
                  ipv4Enabled: true
                  authorizedNetworks:
                  - name: all
                    value: 0.0.0.0/0
      - name: user
        base:
          apiVersion: sql.gcp.m.upbound.io/v1beta1
          kind: User
          spec:
            forProvider:
              passwordSecretRef:
                key: password
                name: my-db-password
              instanceSelector:
                matchControllerRef: true
          