---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-password
  namespace: crossplane-system
data:
  password: cG9zdGdyZXM=
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  name: my-db
  annotations:
    organization: DevOps Toolkit
    author: Carlos Nava
spec:
  id: my-db
  parameters:
    version: "13"
    size: small
  crossplane:
    compositionSelector:
      matchLabels:
        provider: google
        db: postgresql
